### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by greenSnot** [fififish/waterbear#2]
```
$ go install src/main/server.go 
# cryptolib/word
src/cryptolib/word/word.go:22:6: missing function body
src/cryptolib/word/word.go:28:6: missing function body
src/cryptolib/word/word.go:30:6: missing function body
src/cryptolib/word/word.go:36:6: missing function body
src/cryptolib/word/word.go:39:6: missing function body
src/cryptolib/word/word.go:45:6: missing function body
src/cryptolib/word/word.go:47:6: missing function body
src/cryptolib/word/word.go:48:6: missing function body
src/cryptolib/word/word.go:50:6: missing function body
src/cryptolib/word/word.go:56:6: missing function body
src/cryptolib/word/word.go:56:6: too many errors
```

**Comment by fififish** [comment]
which go version are you using? I never met this issue before. I'll double check.

**Comment by greenSnot** [comment]
go version go1.19.4 darwin/arm64

GO111MODULE="auto"
GOARCH="arm64"
GOBIN="/Users/e/Documents/consensus/waterbear/bin"
GOCACHE="/Users/e/Library/Caches/go-build"
GOENV="/Users/e/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/e/Documents/consensus/waterbear/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/e/Documents/consensus/waterbear"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9g/8zmp1y093d3ds0m2lf4rb9jw0000gn/T/go-build3799549479=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by fififish** [comment]
I think the issue is with the darwin/arm64 instance. The word_amd64.s is written for x86 only. To adapt to arm architecture, we need to change the instruction sets written in .s file. Can you find another instance to compile this codebase for now? We will write another one for the arm machines but it will take some time.
