### ISSUE TITLE
Lack of verification of threshold signatures

### ISSUE THREAD

**Issue by yrdsm666** [fififish/waterbear#3]
In src/cryptolib/threshprf/prf_p256.go, the implementation of threshold signature seems to lack verification of threshold signature.

**Comment by fififish** [comment]
It's the Verify_share_node function. Sorry the name is a little bit confusing.

**Comment by yrdsm666** [comment]
Thank you for your answer. There are Compute_share, Verify_share and Compute_prf_from_shares functions in prf_p256.go, but it seems to lack the Verify_prf function. I think the Verify_share_node function just verifies the signature share rather than the threshold signature obtained by combining the shares.

**Comment by fififish** [comment]
We implemented threshold PRF. It's not threshold signature and is thus not transferrable. The combined PRF cannot be verified by other nodes. See this paper for more info: 
Cachin, Kursawe, Shoup. Random Oracles in Constantinople: Practical Asynchronous Byzantine Agreement Using Cryptography. J. Cryptology 2005.
